version: 2
updates:
  - package-ecosystem: terraform
    directory: "/deploy/azure/infra/stacks-aks"
    schedule:
      interval: daily
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
