version: 2
updates:
  - package-ecosystem: terraform
    directory: "/deploy/terraform"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    cooldown:
      default-days: 5
    reviewers:
      - Ensono/stacks-maintainers
    groups:
      terraform-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
