version: 2
updates:
  - package-ecosystem: terraform
    directory: "/deploy/terraform"
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 10
    rebase-strategy: disabled
