apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: stacks-webapp-azure-identity-binding
spec:
  azureIdentity: {{.Values.aks.identity.username}}
  selector: stacks-webapp-identity
