---
:linkTitle: Pipeline
---

== Pipeline

There are two pipelines at work within the repository. The one that is run by the CI/CD platform and ones that are executed by the Ensono Digital Independent Runner (EDIR).

NOTE: The Independent Runner is the main pipeline that is executed, whether it is by a CI/CD platform or on a local machine. The CI/CD pipelines are shims that call the Independent Runner which ensures that the pipeline is executed the same way each time.

=== Independent Runner

The EDIR has a number of pipelines that run a number of tasks.

.EDIR Tasks
|===
| Name | Description
| `build:number` | Update the build number in a pipeline.

Currently knows how to set the build number for Azure DevOps.
| `lint:yaml` | Perform YAML linting on the repository
| `lint:terraform:format` | Perform a Terraform format check
| `lint:terraform:validate` | Validate the Terraform templates
| `infra:init` | Initialise Terraform for the specified templates and backend
| `infra:plan` | Run the Terraform plan to create the plan file which will be used to modify the the resources
| `infra:apply` | Apply the actions as defined by the plan
| `infra:output` | Present the Terraform outputs as a JSON string
| `setup:dev` | Create a shell script which will configure the environment variables based on the `build/config/stage_envvars.yaml`
| `setup:environment` | Ensure that the environment is configured correctly. This can be used to ensure that all the necessary environment variables have been set.
| `tests:infra:init` | Initialse the Inspec test profile. 
| `tests:infra:vendor` | This will analyse the profile and download the required providers to run the tests
| `tests:infra:run` | Execute infrastructure tests against the deployed Cloud Resources using Inspec
| `helm:charts` | Deploy enabled charts to the Kubernetes cluster. More information can be found in the <<Helm>> section.
| `_docs` | Create a PDF file of the documentation.
| `_release` | Create a tag in the GitHub repo when the code is run on the main branch
|===

The tasks are defined in `build/taskctl/tasks.yaml`

.EDIT Pipelines
[cols="1,2,2a",options="header",stripes="even"]
|===
| Name | Description | Flowchart
| lint | Perform all the of the linting tasks for the project.
Yaml and Terraform.

All of the steps in the pipeline are run in parallel where possible. |
[graphviz]
----
include::diagrams/lint.dot[]
----
| tests | Perform infrastructure tests | 
[graphviz]
----
include::diagrams/tests.dot[]
----
| infrastructure | Run Terraform and deploy all of the necessary resources into the target cloud |
[graphviz]
----
include::diagrams/infrastructure.dot[]
----
| docs | Build the documentation |
[graphviz]
----
include::diagrams/documentation.dot[]
----
| release | Runs all of the tasks to create a GitHub release |
[graphviz]
----
include::diagrams/release.dot[]
----
|===

=== Azure DevOps

The following diagram shows the stages and the jobs within each stage for Azure DevOps. Most of the time ADO will call upon the pipelines and tasks in EDIR, but where there is a task that needs to be performed that is specific to ADO a native task will be used.

.Azure DevOps Pipeline Flowchart
[graphviz]
----
include::diagrams/ado_pipeline.dot[]
----

The 4 boxes in the diagram depict the different stages in the pipeline. The cyan coloured boxes are the native tasks to ADo that are used to perform a task. All of the other tasks match up to tasks in the EDIR as describes above.